api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${ACME_EMAIL}"          # берём из .env
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
